@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Group as GroupPackage <<Rectangle>>{
Class Group
Class UniqueCourseMateList
Class CourseMate
Class Name
Class Skill
Class TelegramChat

Class ModelManager
Class GroupList
Class UniqueGroupList

Class I #FFFFFF
}

ModelManager -right-> "1" GroupList
GroupList *--> "1" UniqueGroupList
UniqueGroupList -right-> "* all" Group

UniqueCourseMateList --> "~*" CourseMate

Group --up|> UniqueCourseMateList
Group *--> "1" Name
Group *-> "~*" Skill
Group *--> "0..1" TelegramChat

CourseMate -[hidden]up--> I
UniqueCourseMateList -[hidden]right-> I


@enduml
